Extract download_and_setup_fpc_build_resources utility

diff --git a/build_fpc b/build_fpc
--- a/build_fpc
+++ b/build_fpc
@@ -250,6 +250,75 @@ do_calculate_fpc_opts ()
   fi
 }
 
+# Use this on Windows, around executing "make ..." with Makefile generated
+# by FPCMake.
+# Makefile generated by FPCMake has a few problems on Windows, unless it
+# uses exactly the utilities as provided by FPC.
+download_and_setup_fpc_build_resources ()
+{
+  # Makefile inside FPC has a few problems on Windows.
+  #
+  # Summary:
+  # It's easiest to just avoid them by using utilities (like pwd.exe)
+  # distributed by FPC (here we just reuse them from FPC 3.2.2 installation)
+  # and relying they are placed in a directory without spaces (which is true
+  # at least on GH-hosted Windows runners).
+  # That's what we now do.
+  #
+  # Past problems and attempts:
+  #
+  # 1. At times, FPC Makefile wants native path (not MSys2/Cygwin path).
+  #    This is understandable, but then they try to obtain it by looking for
+  #    /cygdrive prefix and search+replace in Makefile, instead of using more
+  #    reliable "cygpath --mixed ..." to convert paths. The latter would work
+  #    on both MSys2 and Cygwin, and would work for all paths, e.g. /home/...
+  #    (which doesn't start with /cygdrive but is still a Cygwin path).
+  #
+  #    Failing to solve it may result in "make ..." error, and FPC saying it cannot
+  #    find unit system used by pp. You will see it is passing -Fu/cygwin/path
+  #    to ppc*, and thus it's a Cygwin path.
+  #
+  # 2. Makefile inside FPC has problems when `pwd.exe` is present in a directory
+  #    with space in path.
+  #    The Makefile does PWD:=$(strip $(wildcard $(addsuffix /pwd,$(SEARCHPATH))))
+  #    and will fail to find PWD when there is space in path.
+  #    And this is the case on GH-hosted Windows runner, where pwd.exe
+  #    is inside "C:/Program Files/Git/usr/bin/".
+  #
+  #    They could have used "which pwd", which would be more reliable, but didn't...
+  #
+  #    Symptom: "make ..." fails with "You need the GNU utils package to use this Makefile".
+  #
+  #    Solution is to use our ${WORKSPACE_ROOT_UNIX}/fpc-build-resources/install/binwXX .
+
+  git clone https://gitlab.com/freepascal.org/fpc/build.git \
+    -c advice.detachedHead=false \
+    --depth 1 --single-branch --branch main fpc-build-resources
+
+  # check the layout of fpc build repo on
+  # https://gitlab.com/freepascal.org/fpc/build/-/tree/main/install?ref_type=heads
+  local FPC_BUILD_OS_SUBDIR
+  case "${CPU}" in
+    x86_64) FPC_BUILD_OS_SUBDIR=binw64 ;;
+    i386)   FPC_BUILD_OS_SUBDIR=binw32 ;;
+    *)
+      echo "Cannot find FPC_BUILD_OS_SUBDIR for this CPU: ${CPU}"
+      exit 1
+      ;;
+  esac
+
+  # Restore $PATH later, as the FPC utilities are weirdly old.
+  # E.g. `mv.exe` is some archaic version that doesn't tolerate last
+  # parameter having final slash (would fail at "mv ... fpc/bin/",
+  # while the standard "mv" from both MSys2 (in GHA) and Cygwin can handle it).
+  RESTORE_PATH="$PATH"
+
+  # Note that we need to append here to PATH using WORKSPACE_ROOT_UNIX,
+  # not WORKSPACE_ROOT, as in MSys/Cygwin, : is path separator
+  # (not drive letter separator).
+  export PATH="${WORKSPACE_ROOT_UNIX}/fpc-build-resources/install/${FPC_BUILD_OS_SUBDIR}/:$PATH"
+}
+
 do_fpc_build ()
 {
   # Disable broken MSys2 paths conversion,
@@ -261,67 +330,7 @@ do_fpc_build ()
   local FPC_INSTALL_PREFIX="${WORKSPACE_ROOT}/fpc"
 
   if [ "${IS_WINDOWS}" = "true" ]; then
-    # Makefile inside FPC has a few problems on Windows.
-    #
-    # Summary:
-    # It's easiest to just avoid them by using utilities (like pwd.exe)
-    # distributed by FPC (here we just reuse them from FPC 3.2.2 installation)
-    # and relying they are placed in a directory without spaces (which is true
-    # at least on GH-hosted Windows runners).
-    # That's what we now do.
-    #
-    # Past problems and attempts:
-    #
-    # 1. At times, FPC Makefile wants native path (not MSys2/Cygwin path).
-    #    This is understandable, but then they try to obtain it by looking for
-    #    /cygdrive prefix and search+replace in Makefile, instead of using more
-    #    reliable "cygpath --mixed ..." to convert paths. The latter would work
-    #    on both MSys2 and Cygwin, and would work for all paths, e.g. /home/...
-    #    (which doesn't start with /cygdrive but is still a Cygwin path).
-    #
-    #    Failing to solve it may result in "make ..." error, and FPC saying it cannot
-    #    find unit system used by pp. You will see it is passing -Fu/cygwin/path
-    #    to ppc*, and thus it's a Cygwin path.
-    #
-    # 2. Makefile inside FPC has problems when `pwd.exe` is present in a directory
-    #    with space in path.
-    #    The Makefile does PWD:=$(strip $(wildcard $(addsuffix /pwd,$(SEARCHPATH))))
-    #    and will fail to find PWD when there is space in path.
-    #    And this is the case on GH-hosted Windows runner, where pwd.exe
-    #    is inside "C:/Program Files/Git/usr/bin/".
-    #
-    #    They could have used "which pwd", which would be more reliable, but didn't...
-    #
-    #    Symptom: "make ..." fails with "You need the GNU utils package to use this Makefile".
-    #
-    #    Solution is to use our ${WORKSPACE_ROOT_UNIX}/fpc-build-resources/install/binwXX .
-
-    git clone https://gitlab.com/freepascal.org/fpc/build.git \
-      -c advice.detachedHead=false \
-      --depth 1 --single-branch --branch main fpc-build-resources
-
-    # check the layout of fpc build repo on
-    # https://gitlab.com/freepascal.org/fpc/build/-/tree/main/install?ref_type=heads
-    local FPC_BUILD_OS_SUBDIR
-    case "${CPU}" in
-      x86_64) FPC_BUILD_OS_SUBDIR=binw64 ;;
-      i386)   FPC_BUILD_OS_SUBDIR=binw32 ;;
-      *)
-        echo "Cannot find FPC_BUILD_OS_SUBDIR for this CPU: ${CPU}"
-        exit 1
-        ;;
-    esac
-
-    # Restore $PATH later, as the FPC utilities are weirdly old.
-    # E.g. `mv.exe` is some archaic version that doesn't tolerate last
-    # parameter having final slash (would fail at "mv ... fpc/bin/",
-    # while the standard "mv" from both MSys2 (in GHA) and Cygwin can handle it).
-    local RESTORE_PATH="$PATH"
-
-    # Note that we need to append here to PATH using WORKSPACE_ROOT_UNIX,
-    # not WORKSPACE_ROOT, as in MSys/Cygwin, : is path separator
-    # (not drive letter separator).
-    export PATH="${WORKSPACE_ROOT_UNIX}/fpc-build-resources/install/${FPC_BUILD_OS_SUBDIR}/:$PATH"
+    download_and_setup_fpc_build_resources
   fi
 
   cd fpcsrc/
